### PR TITLE
more dynamic url detection to handle reverse proxy

### PR DESCRIPTION
**Pull request by 1000i100**
here is my stack : 
Lufi in docker listening 8181 on localhost.
nginx reverseproxyfing //drop.myhostname/ to localhost:8181

Lufi is accessible at //drop.myhostname/ but ws use localhost:8181 as domain and fail.
This patch fix that.

### CODE REVIEW

**Comment by ldidry** [comment]
Thx but:

1. Contributions have to be done on https://framagit.org/luc/lufi, not on github, which is just a mirror of the framagit repo
1. Your patch prevents to use secure websocket (`wss`).

I think that you're not sending the correct `Host` header to your Lufi. What is your nginx conf? Can you check the recommended configuration on <https://framagit.org/luc/lufi/wikis/installation#putting-lufi-behind-nginx> please?

**Comment by ldidry** [comment]
And did you uncomment `proxy => 1,` in `lufi.conf`?

**Comment by 1000i100** [comment]
yep, i use this `lufi.conf` :
https://github.com/xataz/dockerfiles/tree/master/lufi
with a Dockerfile only changing by this `https://github.com/ContribuLibre/lufi.git` and not `https://git.framasoft.org/luc/lufi.git`

here is my `docker-compose.yml`
```
docker-compose.yml
lufi:
  image: xataz/lufi:latest
  ports:
    - "8181:8080"
  environment:
    - MAX_FILE_SIZE=250000000
    - DEFAULT_DELAY=0
  volumes:
    - /srv/docker/fileDrop/data:/usr/lufi/data
    - /srv/docker/fileDrop/files:/usr/lufi/files
```
and my nginx conf file : 
```
server {
        listen 80;
        server_name {{my-instance}};

        root /nowhere;

        location / {
                proxy_pass http://localhost:8181/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_buffering off;
        }
}
```

**Comment by ldidry** [comment]
You need this in your nginx conf:

```
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

(as said in https://framagit.org/luc/lufi/wikis/installation#putting-lufi-behind-nginx)

**Pull request closed without merging**
