### PR TITLE
Add IaC and ConfigManagement

### PR DESCRIPTION
**Pull request by arunodhayamsam**

### CODE REVIEW

**Comment by arunodhayamsam** [comment]
1. Added the Ansible-Role to deploy the application on Ubuntu 20.04 machine.
2. Added the Terraform plan to provision infrastructure on AWS.

**Comment by ldidry** [comment]
Could you please make your PR on https://framagit.org/fiat-tux/hat-softwares/lufi/ ?

**Comment by arunodhayamsam** [comment]
MR raised
 
https://framagit.org/fiat-tux/hat-softwares/lufi/-/merge_requests/98

**Comment by ldidry** [comment]
All MR have to be done on https://framagit.org/fiat-tux/hat-softwares/lufi/](https://framagit.org/fiat-tux/hat-softwares/lufi/, please.

**Pull request closed without merging**
